version: '3.3'
services:
  firefox:
    #build: .
    build:
      context: .
      args:
        #OS:  innovanon/poodeb-8
        OS: debian
        VER: 8
    hostname: firefox
    #restart: unless-stopped
    volumes:
      - $XAUTHORITY:$XAUTHORITY
      - /tmp/.X11-unix:/tmp/.X11-unix:rw 
      - /etc/localtime:/etc/localtime:rw
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY
    devices:
      - "/dev/snd"
    image: innovanon/docker-firefox:latest
    container_name: docker-firefox

